Repository aalto-grades/aalto-grades, pull requests merged in 2022-12, with the labels that each got.

#43 Docker compose development setup
  README.md
  client/Dockerfile
  docker-compose.yaml
  server/Dockerfile
Labels: frontend, backend, database

#73 Set up unit test environment for backend
  .github/workflows/pr-workflow.yml
  server/README.md
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/index.ts
  server/test/index.test.ts
  server/tsconfig.json
Labels: backend

#48 Initial contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#71 Front page base
  client/README.md
  client/src/App.js
  client/src/components/CourseView.js
  client/src/components/FrontPage.js
  client/src/components/FrontPage/BasicGrid.js
  client/src/components/FrontPage/CourseCard.js
  client/src/components/FrontPage/CourseHeadTableRow.js
  client/src/components/FrontPage/CourseTable.js
  client/src/components/FrontPage/CourseTableRow.js
  client/src/components/Info.js
  client/src/components/Main.js
  client/src/services/axios.js
  client/src/services/courses.js
  client/src/services/sorting.js
  client/src/tests/Main.test.js
  client/src/tests/index.test.js
  server/package-lock.json
  server/package.json
  server/src/index.ts
  server/src/services/README.md
  server/src/services/courses.ts
Labels: frontend, backend

#81 Bump up password storage size
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/user.ts
Labels: bug, backend, database

#80 Fix off-by-one error in seed:down
  server/src/database/seeders/001-dummy-data.ts
Labels: bug, backend, database
