Repository aalto-grades/aalto-grades, pull requests merged in 2023-06, with the labels that each got.

#248 Basic error logging
  server/mock-data/attainable.sql
  server/mock-data/course_instance_roles.sql
  server/mock-data/course_instances.sql
  server/mock-data/course_result.sql
  server/mock-data/course_translations.sql
  server/mock-data/courses.sql
  server/mock-data/user_attainment_grade.sql
  server/mock-data/users.sql
  server/src/database/seeders/001-dummy-data.ts
  server/src/middleware/errorHandler.ts
Labels: backend

#252 API to get all courses
  server/src/controllers/course.ts
  server/src/routes/course.ts
  server/src/routes/index.ts
  server/test/controllers/course.test.ts
Labels: backend

#254 Admin front page
  client/src/App.tsx
  client/src/components/AllCoursesView.tsx
  client/src/components/FrontPage.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/Signup.tsx
  client/src/context/authProvider.tsx
  client/src/mock-data/mockCourses.tsx
  client/src/services/courses.tsx
  client/src/tests/AllCoursesView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/FrontPage.test.tsx
Labels: frontend

#251 System level auth
  client/src/App.tsx
  client/src/components/AllCoursesView.tsx
  client/src/components/CourseView.tsx
  client/src/components/FrontPage.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/SignupForm.tsx
  client/src/tests/AllCoursesView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/Signup.test.tsx
  client/src/tests/UserButton.test.tsx
  client/src/types/general.ts
  robot-tests/authentication/variables.robot
  server/mock-data/users.sql
  server/src/controllers/auth.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/user.ts
  server/src/middleware/authorization.ts
  server/src/routes/attainable.ts
  server/src/routes/auth.ts
  server/src/routes/course.ts
  server/src/routes/courseInstance.ts
  server/src/routes/grades.ts
  server/src/routes/sisu.ts
  server/src/routes/user.ts
  server/src/types/general.ts
  server/test/controllers/attainable.test.ts
  server/test/controllers/auth.test.ts
  server/test/controllers/course.test.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/grades.test.ts
  server/test/controllers/sisu.test.ts
  server/test/controllers/user.test.ts
  server/test/util/getCookies.ts
Labels: backend

#257 Remove the term "student ID"
  client/src/components/auth/SignupForm.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/mock-data/mockStudentGrades.tsx
  client/src/mock-data/mockStudentGradesFinal.tsx
  client/src/tests/CourseResultsView.test.tsx
  client/src/tests/Signup.test.tsx
  server/mock-data/users.sql
  server/src/controllers/auth.ts
  server/src/controllers/grades.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00002-add-indexes.ts
  server/src/database/models/user.ts
  server/src/routes/auth.ts
  server/test/controllers/auth.test.ts
  server/test/controllers/grades.test.ts
  server/test/util/getCookies.ts
Labels: frontend, backend

#259 Common types module
  .reuse/dep5
  client/Dockerfile
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/AllCoursesView.tsx
  client/src/components/CourseView.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/SignupForm.tsx
  client/src/components/create-course-view/CreateCourseForm.tsx
  client/src/mock-data/mockCourses.tsx
  client/src/services/courses.tsx
  client/src/tests/AllCoursesView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/FrontPage.test.tsx
  client/src/tests/Signup.test.tsx
  client/src/tests/UserButton.test.tsx
  client/src/types/general.ts
  common-services.yaml
  common/.gitignore
  common/package.json
  common/types/course.ts
  common/types/general.ts
  common/types/language.ts
  docker-compose.yaml
  server/Dockerfile
  server/package-lock.json
  server/package.json
  server/src/controllers/course.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/grades.ts
  server/src/controllers/sisu.ts
  server/src/controllers/user.ts
  server/src/types/language.ts
  server/src/types/sisu.ts
  server/test/controllers/sisu.test.ts
Labels: frontend, backend

#262 Fix package build
  .github/workflows/main-merge-workflow.yaml
  client/Dockerfile.prod
  client/package.json
  reverse-proxy/Dockerfile
Labels: bug, github

#263 Allow removing attaiments in instance creation
  client/src/components/AddAttainmentsView.tsx
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/tests/AddAttainmentsView.test.tsx
  server/docker-compose.yaml
Labels: frontend

#267 Get single attainment
  server/mock-data/attainment.sql
  server/mock-data/user_attainment_grade.sql
  server/package-lock.json
  server/src/controllers/attainable.ts
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/attainable.ts
  server/src/controllers/utils/attainment.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00002-add-indexes.ts
  server/src/database/models/attainment.ts
  server/src/database/models/index.ts
  server/src/database/models/userAttainmentGrade.ts
  server/src/database/seeders/001-dummy-data.ts
  server/src/routes/attainment.ts
  server/src/routes/grades.ts
  server/src/routes/index.ts
  server/src/types/attainment.ts
  server/src/types/grades.ts
  server/test/controllers/attainment.test.ts
  server/test/controllers/grades.test.ts
  server/test/functions/csvParsing.test.ts
  server/test/mockData/attainment.ts
  server/test/mockData/csv/grades_non_existing_attainments.csv
Labels: backend

#266 Allow cancelling course instance creation
  client/src/components/AddAttainmentsView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/edit-instance-view/EditInstanceForm.tsx
  client/src/components/fetch-instances-view/FetchedInstances.tsx
  client/src/mock-data/mockAttainmentsClient.tsx
  client/src/tests/FetchInstances.test.tsx
Labels: frontend

#269 User definable tags for attainments
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/controllers/utils/attainment.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00003-add-constraints.ts
  server/src/database/models/attainment.ts
  server/src/types/attainment.ts
  server/test/controllers/attainment.test.ts
  server/test/mock-data/attainment.ts
Labels: backend, database

#271 API to get course instance final grades in JSON format.
  server/src/controllers/grades.ts
  server/src/routes/grades.ts
  server/test/controllers/grades.test.ts
Labels: backend

#279 Update documentation
  CONTRIBUTING.md
  README.md
  client/README.md
  common/README.md
  server/README.md
Labels: documentation

#278 Get final grades from server
  client/src/components/CourseResultsView.tsx
  client/src/components/alerts/AlertSnackbar.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/components/course-view/FileLoadDialog.tsx
  client/src/mock-data/mockStudentGrades.tsx
  client/src/mock-data/mockStudentGradesFinal.tsx
  client/src/services/grades.tsx
  server/src/routes/grades.ts
Labels: frontend

#280 CSV template download button
  client/src/components/CourseResultsView.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/SisuExportDialog.tsx
  client/src/components/course-view/FileLoadDialog.tsx
  client/src/services/grades.tsx
  client/src/tests/FileLoadDialog.test.tsx
Labels: frontend

#272 Frontend strict TypeScript start
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/AddAttainmentsView.tsx
  client/src/components/AllCoursesView.tsx
  client/src/components/CourseView.tsx
  client/src/components/CreateAttainmentView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/InstanceSummaryView.tsx
  client/src/components/SelectFormulaView.tsx
  client/src/components/alerts/AlertSnackbar.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/LoginForm.tsx
  client/src/components/auth/PrivateRoute.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/SignupForm.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/SisuExportDialog.tsx
  client/src/components/course-view/FileLoadDialog.tsx
  client/src/components/course-view/MenuButton.tsx
  client/src/components/create-attainment/LeafAttainment.tsx
  client/src/components/create-attainment/ParentAttainment.tsx
  client/src/components/edit-instance-view/EditInstanceForm.tsx
  client/src/components/fetch-instances-view/FetchedInstances.tsx
  client/src/components/front-page/CourseCard.tsx
  client/src/components/front-page/CourseTableRow.tsx
  client/src/components/select-formula-view/SelectFormulaForm.tsx
  client/src/services/attainments.tsx
  client/src/services/courses.tsx
  client/src/services/grades.tsx
  client/src/services/instances.tsx
  client/src/services/sorting.tsx
  client/src/services/textFormat.tsx
  client/src/services/user.tsx
  client/src/tests/AllCoursesView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/CreateAttainmentView.test.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/EditInstance.test.tsx
  client/src/tests/FetchInstances.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/InstanceSummaryView.test.tsx
  client/src/tests/SelectFormulaView.test.tsx
  client/src/tests/Signup.test.tsx
  client/src/tests/UserButton.test.tsx
  client/src/types/auth.tsx
  client/src/types/general.tsx
  common/types/auth.ts
  server/src/controllers/auth.ts
  server/src/middleware/authorization.ts
  server/src/routes/course.ts
  server/src/routes/courseInstance.ts
  server/src/types/general.ts
  server/test/controllers/auth.test.ts
  server/test/util/getCookies.ts
Labels: frontend

#283 Distinguish manual and calculated attainment grades
  server/mock-data/attainment.sql
  server/mock-data/user_attainment_grade.sql
  server/src/controllers/grades.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/userAttainmentGrade.ts
  server/test/controllers/grades.test.ts
  server/test/mock-data/csv/grades_one.csv
Labels: backend, database

#287 Parent ID in attainment model
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00002-add-indexes.ts
  server/src/database/models/attainment.ts
  server/src/database/models/index.ts
Labels: enhancement, backend, database

#300 Better course and instance service typings
  client/.eslintrc.json
  client/src/components/AddAttainmentsView.tsx
  client/src/components/AllCoursesView.tsx
  client/src/components/CourseView.tsx
  client/src/components/CreateCourseView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/FrontPage.tsx
  client/src/components/InstanceSummaryView.tsx
  client/src/components/SelectFormulaView.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/auth/PrivateRoute.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/components/course-view/FileLoadDialog.tsx
  client/src/components/create-course-view/CreateCourseForm.tsx
  client/src/services/courses.tsx
  client/src/services/instances.tsx
  client/src/tests/AddAttainmentsView.test.tsx
  client/src/tests/AllCoursesView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/EditInstance.test.tsx
  client/src/tests/FetchInstances.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/FrontPage.test.tsx
  client/src/tests/InstanceSummaryView.test.tsx
  common/types/course.ts
  server/src/controllers/grades.ts
  server/src/controllers/user.ts
  server/test/controllers/grades.test.ts
  server/test/controllers/user.test.ts
Labels: frontend

#302 Get assessment model
  server/src/controllers/assessmentModel.ts
  server/src/routes/assessmentModel.ts
  server/src/routes/index.ts
  server/src/types/attainment.ts
  server/test/controllers/assessmentModel.test.ts
Labels: backend

#305 Get all assessment models of course
  client/.eslintrc.json
  server/mock-data/courses.sql
  server/src/controllers/assessmentModel.ts
  server/src/routes/assessmentModel.ts
  server/test/controllers/assessmentModel.test.ts
Labels: backend

#308 Assessment model services
  client/src/services/assessmentModels.tsx
  client/src/services/attainments.tsx
  client/src/types/general.tsx
Labels: frontend

#309 Course view with assessment model
  .github/workflows/pr-workflow.yaml
  client/src/components/AddAttainmentsView.tsx
  client/src/components/AllCoursesView.tsx
  client/src/components/CourseResultsView.tsx
  client/src/components/CourseView.tsx
  client/src/components/CreateAttainmentView.tsx
  client/src/components/CreateCourseView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/FormulaAttributesView.tsx
  client/src/components/InstanceSummaryView.tsx
  client/src/components/SelectFormulaView.tsx
  client/src/components/alerts/AlertSnackbar.tsx
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/UserButton.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/SisuExportDialog.tsx
  client/src/components/course-view/AssessmentModelsTable.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/components/course-view/FileLoadDialog.tsx
  client/src/components/course-view/InstanceTableHead.tsx
  client/src/components/course-view/InstanceTableRow.tsx
  client/src/components/course-view/InstancesTable.tsx
  client/src/components/create-attainment/ParentAttainment.tsx
  client/src/components/edit-instance-view/EditInstanceForm.tsx
  client/src/components/fetch-instances-view/FetchedInstances.tsx
  client/src/components/front-page/CourseCard.tsx
  client/src/components/front-page/CourseTableRow.tsx
  client/src/components/select-formula-view/SelectFormulaForm.tsx
  client/src/context/AuthProvider.tsx
  client/src/context/InstanceCreationRoute.tsx
  client/src/hooks/useAuth.tsx
  client/src/index.tsx
  client/src/services/assessmentModels.tsx
  client/src/services/attainments.tsx
  client/src/services/courses.tsx
  client/src/services/instances.tsx
  client/src/services/user.tsx
  client/src/tests/AllCoursesView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/FrontPage.test.tsx
  client/src/tests/SelectFormulaView.test.tsx
  client/src/tests/UserButton.test.tsx
  client/src/types/index.tsx
  common/types/index.ts
Labels: frontend

#312 Course view new design
  .github/workflows/pr-workflow.yaml
  client/src/components/CourseView.tsx
  client/src/components/CreateCourseView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/InstanceSummaryView.tsx
  client/src/components/course-view/AssessmentModelsList.tsx
  client/src/components/course-view/AssessmentModelsTable.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/components/course-view/InstanceDetails.tsx
  client/src/components/course-view/InstancesTable.tsx
  client/src/components/create-course-view/CreateCourseForm.tsx
  client/src/components/create-course-view/TextFieldBox.tsx
  client/src/mock-data/mockAttainmentsClient.tsx
  client/src/services/attainments.tsx
  client/src/tests/AddAttainmentsView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/CreateCourse.test.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/InstanceSummaryView.test.tsx
  client/src/tests/mock-data/mockAssessmentModels.tsx
  client/src/tests/mock-data/mockAttainmentsClient.tsx
Labels: frontend

#314 Update front page
  client/src/App.tsx
  client/src/components/AllCoursesView.tsx
  client/src/components/FrontPage.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/front-page/BasicGrid.tsx
  client/src/components/front-page/CourseCard.tsx
  client/src/index.tsx
  client/src/services/courses.tsx
  client/src/services/grades.tsx
  client/src/services/sorting.tsx
  client/src/tests/AllCoursesView.test.tsx
  client/src/tests/CourseResultsView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/EditInstance.test.tsx
  client/src/tests/FetchInstances.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/FormulaAttributesView.test.tsx
  client/src/tests/FrontPage.test.tsx
  client/src/tests/Login.test.tsx
  client/src/tests/SelectFormulaView.test.tsx
  client/src/tests/Signup.test.tsx
  client/src/tests/UserButton.test.tsx
  client/src/tests/mock-data/mockInstancesWithStringDates.tsx
  common/types/user.ts
  server/mock-data/course_instance_roles.sql
  server/mock-data/teachers_in_charge.sql
  server/mock-data/users.sql
  server/src/controllers/user.ts
  server/src/routes/course.ts
  server/src/routes/user.ts
  server/test/controllers/course.test.ts
  server/test/controllers/user.test.ts
Labels: frontend, backend

#290 GET formula from server
  client/src/components/CourseResultsView.tsx
  client/src/components/InstanceSummaryView.tsx
  client/src/components/SelectFormulaView.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/create-attainment/ParentAttainment.tsx
  client/src/components/formula-attributes-view/Attainment.tsx
  client/src/components/formula-attributes-view/FormulaAttributesForm.tsx
  client/src/components/select-formula-view/SelectFormulaForm.tsx
  client/src/components/select-formula-view/ViewFormulaAccordion.tsx
  client/src/hooks/useSnackPackAlerts.tsx
  client/src/services/attainments.tsx
  client/src/services/formulas.tsx
  client/src/tests/FormulaAttributesView.test.tsx
  client/src/tests/SelectFormulaView.test.tsx
  client/src/tests/mock-data/mockAttainments.tsx
  client/src/tests/mock-data/mockFormulas.tsx
  client/src/utils/index.ts
  common/types/formula.ts
  common/types/index.ts
  server/src/controllers/attainment.ts
  server/src/controllers/formula.ts
  server/src/controllers/grades.ts
  server/src/database/models/attainment.ts
  server/src/formulas/index.ts
  server/src/formulas/manual.ts
  server/src/formulas/weightedAverage.ts
  server/src/routes/formula.ts
  server/src/routes/index.ts
  server/src/types/formulas.ts
  server/test/controllers/formula.test.ts
  server/test/formulas/weightedAverage.test.ts
Labels: backend

#318 Show tags in the course view attainment list
  client/src/components/CourseView.tsx
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/mock-data/mockAttainmentsClient.tsx
Labels: frontend
