Repository aalto-grades/aalto-grades, pull requests merged in 2023-03, with the labels that each got.

#153 APIs for adding and editing attainments
  server/mockData/attainable.sql
  server/src/controllers/attainable.ts
  server/src/controllers/utils/attainable.ts
  server/src/controllers/utils/courseInstance.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00002-add-indexes.ts
  server/src/database/migrations/00003-add-constraints.ts
  server/src/database/models/attainable.ts
  server/src/database/models/courseAssignment.ts
  server/src/database/models/index.ts
  server/src/database/models/userAttainmentGrade.ts
  server/src/database/models/userPartialGrade.ts
  server/src/database/seeders/001-dummy-data.ts
  server/src/routes/attainable.ts
  server/src/routes/index.ts
  server/src/types/attainable.ts
  server/test/controllers/attainable.test.ts
  server/test/controllers/sisu.test.ts
  server/test/mockData/attainable.ts
  server/test/mockData/sisu.ts
Labels: backend, database

#168 Include course ID in all course instance routes
  server/src/controllers/course.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/utils/course.ts
  server/src/routes/courseInstance.ts
  server/test/controllers/courseInstance.test.ts
Labels: backend

#169 Fix typo in environment variable
  server/src/configs/environment.ts
Labels: backend

#172 Fix coverage reporting in server Dockerfile
  docker-tests/docker-compose.yaml
  server/Dockerfile
Labels: bug, backend

#174 Use Object.values for yup enum validation
  server/src/controllers/auth.ts
  server/src/controllers/courseInstance.ts
Labels: backend

#171 Formula attributes view
  client/src/App.js
  client/src/components/FormulaAttributesView.js
  client/src/components/SelectFormulaView.js
  client/src/components/course-view/Assignments.js
  client/src/components/formula-attributes-view/Assignment.js
  client/src/components/formula-attributes-view/FormulaAttributesForm.js
  client/src/components/select-formula-view/SelectFormulaForm.js
  client/src/components/select-formula-view/StyledBox.js
  client/src/context/FormulaSelectionRoute.js
  client/src/tests/FormulaAttributesView.test.js
  client/src/tests/SelectFormulaView.test.js
Labels: frontend

#180 update sequelize setup
  server/src/database/index.ts
Labels: backend

#177 Course view improvements
  client/src/App.js
  client/src/components/AddAssignmentsView.js
  client/src/components/CourseView.js
  client/src/components/EditInstanceView.js
  client/src/components/FetchInstancesView.js
  client/src/components/InstanceSummaryView.js
  client/src/components/course-view/InstanceDetails.js
  client/src/components/course-view/InstanceTableRow.js
  client/src/components/course-view/InstancesTable.js
  client/src/components/edit-instance-view/EditInstanceForm.js
  client/src/components/front-page/CourseCard.js
  client/src/components/front-page/CourseTableRow.js
  client/src/mock-data/mockAssignmentsClient.js
  client/src/mock-data/mockInstancesWithStringDates.js
  client/src/services/courses.js
  client/src/services/instances.js
  client/src/tests/CourseView.test.js
  server/package-lock.json
Labels: frontend

#181 API for adding grade data through a CSV file
  .reuse/dep5
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/src/controllers/course.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/courseInstance.ts
  server/src/middleware/errorHandler.ts
  server/src/routes/grades.ts
  server/src/routes/index.ts
  server/test/controllers/grades.test.ts
  server/test/mockData/csv/grades.csv
  server/test/mockData/csv/grades_invalid_row.csv
  server/test/mockData/csv/wrong_file_type.txt
Labels: backend
