Repository aalto-grades/aalto-grades, pull requests merged in 2023-02, with the labels that each got.

#139 Speed up Docker by performing chown as part of COPY
  client/Dockerfile
  docker-compose.yaml
  server/Dockerfile
Labels: enhancement, frontend, backend

#140 Implement session expiry in backend
  server/package-lock.json
  server/package.json
  server/src/configs/config.ts
  server/src/routes/login.ts
  server/test/routes/auth.test.ts
Labels: backend

#141 Swagger setup
  server/README.md
  server/package-lock.json
  server/package.json
  server/src/configs/swagger.ts
  server/src/routes/index.ts
Labels: backend, critical

#145 Update auth routes to match specification
  client/src/components/auth/Login.js
  client/src/components/auth/Signup.js
  client/src/components/auth/SignupForm.js
  client/src/tests/Signup.test.js
  server/src/controllers/auth.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/user.ts
  server/src/routes/login.ts
  server/test/routes/auth.test.ts
Labels: frontend, backend, database

#142 Update sisu routes
  server/mockdata/course_instances.sql
  server/src/controllers/course.ts
  server/src/controllers/user.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/courseInstance.ts
  server/src/routes/index.ts
  server/test/routes/index.test.ts
Labels: backend, database

#128 Routes course instances
  server/package-lock.json
  server/src/controllers/courseInstance.ts
  server/src/database/models/index.ts
  server/src/routes/index.ts
  server/test/controllers/courseInstance.test.ts
Labels: backend, critical, database

#149 Update ID schema to ensure ID is positive
  server/src/types/general.ts
  server/test/controllers/course.test.ts
  server/test/controllers/courseInstance.test.ts
Labels: backend

#148 Add nonblock statement ESLint rule
  server/.eslintrc.json
Labels: backend

#146 Custom error classes
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/auth.ts
  server/src/controllers/course.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/sisu.ts
  server/src/controllers/user.ts
  server/src/controllers/utils/course.ts
  server/src/controllers/utils/user.ts
  server/src/middleware/errorHandler.ts
  server/src/routes/auth.ts
  server/src/routes/index.ts
  server/src/types/error.ts
  server/src/types/httpCode.ts
  server/test/controllers/auth.test.ts
  server/test/controllers/course.test.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/sisu.test.ts
  server/test/controllers/user.test.ts
Labels: backend, critical

#151 User route documentation
  server/src/controllers/user.ts
  server/src/routes/index.ts
  server/src/routes/user.ts
Labels: documentation, backend

#150 Course instance refactoring and documentation
  server/src/configs/swagger.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/sisu.ts
  server/src/controllers/user.ts
  server/src/controllers/utils/course.ts
  server/src/controllers/utils/user.ts
  server/src/routes/courseInstance.ts
  server/src/routes/index.ts
  server/src/types/course.ts
  server/src/types/httpCode.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/sisu.test.ts
Labels: documentation, backend

#156 Fixes to account for backend changes
  client/src/components/EditInstanceView.js
  client/src/components/FetchInstancesView.js
  client/src/components/auth/PrivateRoute.js
  client/src/components/edit-instance-view/EditInstanceForm.js
  client/src/components/fetch-instances-view/FetchedInstances.js
  client/src/mock-data/mockSisuInstances.js
  client/src/services/courses.js
  client/src/services/instances.js
  client/src/tests/EditInstance.test.js
  client/src/tests/FetchInstances.test.js
Labels: frontend

#152 Create assignment view
  client/Dockerfile
  client/src/App.js
  client/src/components/CourseView.js
  client/src/components/CreateAssignmentView.js
  client/src/components/course-view/Assignments.js
  client/src/components/create-assignment/Assignment.js
  client/src/components/create-assignment/ConfirmationDialog.js
  client/src/components/create-assignment/DateTextField.js
  client/src/components/create-assignment/LeafAssignment.js
  client/src/components/create-assignment/ParentAssignment.js
  client/src/components/create-assignment/SimpleDialog.js
  client/src/components/create-assignment/StringTextField.js
  client/src/services/assignments.js
  client/src/tests/CreateAssignmentView.test.js
Labels: frontend

#157 Formula selection
  client/src/App.js
  client/src/components/SelectFormulaView.js
  client/src/components/select-formula-view/SelectFormulaForm.js
  client/src/components/select-formula-view/ViewFormulaAccordion.js
  client/src/mock-data/mockAssignments.js
  client/src/mock-data/mockFormulas.js
  client/src/services/formulas.js
  client/src/services/instances.js
  client/src/tests/SelectFormulaView.test.js
Labels: frontend

#154 Course refactoring and documentation
  server/src/configs/swagger.ts
  server/src/controllers/course.ts
  server/src/routes/course.ts
  server/src/routes/courseInstance.ts
  server/src/routes/index.ts
  server/test/controllers/course.test.ts
Labels: documentation, backend

#158 Instance creation pages
  client/src/App.js
  client/src/components/AddAssignmentsView.js
  client/src/components/CourseView.js
  client/src/components/EditInstanceView.js
  client/src/components/InstanceSummaryView.js
  client/src/components/alerts/AlertSnackbar.js
  client/src/components/assignments/Accordion.js
  client/src/components/assignments/AssignmentCategory.js
  client/src/components/course-view/Assignments.js
  client/src/components/edit-instance-view/EditInstanceForm.js
  client/src/components/fetch-instances-view/FetchedInstances.js
  client/src/components/typography/LightLabelBoldValue.js
  client/src/context/InstanceCreationRoute.js
  client/src/mock-data/mockSuggestedAssignments.js
  client/src/tests/AddAssignmentsView.test.js
  client/src/tests/EditInstance.test.js
  client/src/tests/InstanceSummaryView.test.js
Labels: frontend

#155 Sisu refactoring and documentation
  server/src/controllers/sisu.ts
  server/src/routes/index.ts
  server/src/routes/sisu.ts
Labels: documentation, backend

#164 Create client side assignment mock data
  client/src/components/AddAssignmentsView.js
  client/src/components/CourseView.js
  client/src/components/InstanceSummaryView.js
  client/src/components/assignments/Accordion.js
  client/src/components/assignments/AssignmentCategory.js
  client/src/components/course-view/Assignments.js
  client/src/mock-data/mockAssignmentsClient.js
  client/src/mock-data/mockAssignmentsServer.js
  client/src/services/formulas.js
  client/src/tests/AddAssignmentsView.test.js
  client/src/tests/CourseView.test.js
Labels: frontend
