Repository aalto-grades/aalto-grades, pull requests merged in 2023-08, with the labels that each got.

#405 Course editing API endpoint
  server/mock-data/course_translations.sql
  server/mock-data/courses.sql
  server/mock-data/teachers_in_charge.sql
  server/src/controllers/course.ts
  server/src/routes/course.ts
  server/test/controllers/course.test.ts
Labels: backend

#404 Display grades of student for each attainment in an assessment model
  client/src/components/CourseResultsView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/StudentGradeAccordion.tsx
  client/src/components/course-results-view/StudentGradeList.tsx
  client/src/components/course-results-view/StudentGradesDialog.tsx
  client/src/hooks/api/grade.ts
  client/src/tests/mock-data/mockFinalGrades.tsx
  common/types/grades.ts
  server/src/controllers/grades.ts
  server/src/routes/attainment.ts
  server/src/routes/grades.ts
  server/src/routes/index.ts
  server/src/routes/user.ts
  server/test/controllers/grades.test.ts
Labels: enhancement, frontend, backend

#415 Helmet ExpressJS middleware
  server/package-lock.json
  server/package.json
  server/src/app.ts
Labels: backend

#417 Remove PropTypes
  client/package-lock.json
  client/package.json
  client/src/components/alerts/AlertSnackbar.tsx
  client/src/components/alerts/UnsavedChangesDialog.tsx
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/auth/PrivateRoute.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/components/course-results-view/FileErrorDialog.tsx
  client/src/components/course-results-view/FileLoadDialog.tsx
  client/src/components/course-results-view/MenuButton.tsx
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  client/src/components/course-results-view/StudentGradeAccordion.tsx
  client/src/components/course-results-view/StudentGradesDialog.tsx
  client/src/components/course-view/AssessmentModelsList.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
  client/src/components/course-view/InstancesTable.tsx
  client/src/components/edit-attainment-view/Attainment.tsx
  client/src/components/edit-attainment-view/ConfirmationDialog.tsx
  client/src/components/edit-attainment-view/LeafAttainment.tsx
  client/src/components/edit-attainment-view/ParentAttainment.tsx
  client/src/components/edit-attainment-view/SimpleDialog.tsx
  client/src/components/edit-attainment-view/StringTextField.tsx
  client/src/components/edit-formula-dialog/EditFormulaDialog.tsx
  client/src/components/edit-formula-dialog/FormulaSummary.tsx
  client/src/components/edit-formula-dialog/SelectFormula.tsx
  client/src/components/edit-formula-dialog/SetFormulaParams.tsx
  client/src/components/edit-formula-dialog/SubAttainment.tsx
  client/src/components/fetch-instances-view/FetchedInstances.tsx
  client/src/components/front-page/CourseTable.tsx
  client/src/components/typography/LightLabelBoldValue.tsx
  client/src/context/AuthProvider.tsx
Labels: frontend

#416 Update buttons, rename organizer to organizing department
  client/.eslintrc.json
  client/src/components/CreateCourseView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/auth/ExternalAuth.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/FileLoadDialog.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/components/edit-attainment-view/Attainment.tsx
  client/src/components/edit-attainment-view/ConfirmationDialog.tsx
  client/src/components/edit-attainment-view/LeafAttainment.tsx
  client/src/components/edit-attainment-view/ParentAttainment.tsx
  client/src/components/edit-attainment-view/SimpleDialog.tsx
  client/src/components/edit-attainment-view/StringTextField.tsx
  client/src/components/front-page/CourseTable.tsx
  client/src/tests/CourseResultsView.test.tsx
  client/src/tests/CreateCourse.test.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/EditInstance.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  server/.eslintrc.json
Labels: enhancement, frontend

#414 Edit course view
  client/package.json
  client/src/App.tsx
  client/src/components/CourseView.tsx
  client/src/components/CreateCourseView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/EditCourseView.tsx
  client/src/components/FrontPage.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/hooks/api/course.ts
  client/src/tests/EditCourseView.test.tsx
  server/src/controllers/course.ts
  server/src/controllers/utils/course.ts
  server/src/routes/course.ts
  server/test/controllers/course.test.ts
Labels: frontend

#432 Remove attainment tags
  client/src/components/EditAttainmentView.tsx
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/FileLoadDialog.tsx
  client/src/components/course-results-view/StudentGradeAccordion.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
  client/src/components/edit-attainment-view/LeafAttainment.tsx
  client/src/components/edit-attainment-view/ParentAttainment.tsx
  client/src/components/edit-attainment-view/SimpleDialog.tsx
  client/src/components/edit-formula-dialog/SetFormulaParams.tsx
  client/src/components/edit-formula-dialog/SubAttainment.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/mock-data/mockAttainments.tsx
  common/types/attainment.ts
  common/types/grades.ts
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/attainment.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00003-add-constraints.ts
  server/src/database/models/attainment.ts
  server/src/formulas/manual.ts
  server/src/formulas/weightedAverage.ts
  server/src/routes/attainment.ts
  server/src/routes/grades.ts
  server/src/types/formulas.ts
  server/test/controllers/attainment.test.ts
  server/test/controllers/grades.test.ts
  server/test/formulas/weightedAverage.test.ts
  server/test/functions/csvParsing.test.ts
  server/test/mock-data/attainment.ts
  server/test/mock-data/csv/grades.csv
  server/test/mock-data/csv/grades_big.csv
  server/test/mock-data/csv/grades_incorrect_grade_rows.csv
  server/test/mock-data/csv/grades_incorrect_header_columns.csv
  server/test/mock-data/csv/grades_invalid_row.csv
  server/test/mock-data/csv/grades_non-existing_students.csv
  server/test/mock-data/csv/grades_non_existing_attainments.csv
  server/test/mock-data/csv/grades_one.csv
  server/test/mock-data/csv/grades_one_2.csv
  server/test/mock-data/csv/grades_teacher_in_row.csv
  server/test/mock-data/csv/grades_updated.csv
  server/test/mock-data/csv/wrong_file_type.txt
Labels: frontend, backend, database

#436 Add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: github

#440 Fix issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .reuse/dep5
Labels: bug, github

#441 Can't export grades after calculating grades
  client/src/components/CourseResultsView.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
Labels: bug, frontend

#439 Invalidate queries in mutations
  client/src/components/CourseResultsView.tsx
  client/src/components/EditCourseView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/course-results-view/FileLoadDialog.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
  client/src/hooks/api/assessmentModel.ts
  client/src/hooks/api/attainment.ts
  client/src/hooks/api/auth.ts
  client/src/hooks/api/course.ts
  client/src/hooks/api/grade.ts
  client/src/hooks/api/instance.ts
  client/src/types/index.ts
Labels: frontend

#446 Assessment model template
  client/src/components/CourseView.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
Labels: enhancement, frontend

#452 Edit attainment API
  server/src/controllers/grades.ts
  server/src/controllers/utils/attainment.ts
  server/src/routes/grades.ts
  server/src/routes/index.ts
  server/test/controllers/grades.test.ts
Labels: backend

#445 Consider multiple grades for the same attainment in API
  client/src/components/CourseResultsView.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/StudentGradeAccordion.tsx
  client/src/components/course-results-view/StudentGradeList.tsx
  client/src/tests/mock-data/mockFinalGrades.tsx
  common/types/grades.ts
  server/mock-data/assessment_model.sql
  server/mock-data/attainment.sql
  server/mock-data/attainment_grade.sql
  server/src/controllers/grades.ts
  server/src/routes/grades.ts
  server/src/types/grades.ts
  server/test/controllers/grades.test.ts
  server/test/functions/csvParsing.test.ts
  server/test/mock-data/csv/grades_multiple_uploads_1.csv
  server/test/mock-data/csv/grades_multiple_uploads_2.csv
Labels: frontend, backend

#456 Manual formula params
  client/.eslintrc.json
  client/src/components/EditAttainmentView.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
  client/src/components/edit-attainment-view/LeafAttainment.tsx
  client/src/components/edit-attainment-view/ParentAttainment.tsx
  client/src/components/edit-attainment-view/SimpleDialog.tsx
  client/src/components/edit-formula-dialog/EditFormulaDialog.tsx
  client/src/components/edit-formula-dialog/SetFormulaParams.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/mock-data/mockAttainments.tsx
  common/types/attainment.ts
  common/types/formula.ts
  server/.eslintrc.json
  server/mock-data/assessment_model.sql
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/attainment.ts
  server/src/formulas/index.ts
  server/src/formulas/manual.ts
  server/src/formulas/weightedAverage.ts
  server/src/middleware/errorHandler.ts
  server/src/types/formulas.ts
  server/test/controllers/attainment.test.ts
  server/test/controllers/grades.test.ts
  server/test/functions/csvParsing.test.ts
  server/test/mock-data/attainment.ts
  server/test/mock-data/csv/grades_failing_manual.csv
  server/test/mock-data/csv/grades_failing_non_manual.csv
Labels: frontend, backend

#466 Attainments in course results
  client/src/components/CourseResultsView.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/components/course-results-view/CourseResultsTableRow.tsx
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
Labels: frontend

#470 Make grading scale course specific
  client/src/components/EditCourseView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/components/course-view/InstancesTable.tsx
  client/src/tests/EditCourseView.test.tsx
  client/src/tests/EditInstance.test.tsx
  client/src/tests/mock-data/mockCourses.tsx
  client/src/tests/mock-data/mockInstancesWithStringDates.tsx
  client/src/tests/mock-data/mockSisuInstances.tsx
  common/types/course.ts
  server/mock-data/course_instances.sql
  server/mock-data/courses.sql
  server/src/controllers/course.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/sisu.ts
  server/src/controllers/utils/course.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/course.ts
  server/src/database/models/courseInstance.ts
  server/test/controllers/course.test.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/sisu.test.ts
  server/test/controllers/user.test.ts
Labels: frontend, backend

#469 Remove evaluation information
  client/src/tests/mock-data/mockCourses.tsx
  client/src/tests/mock-data/mockInstancesWithStringDates.tsx
  client/src/tests/mock-data/mockSisuInstances.tsx
  common/types/course.ts
  server/src/controllers/sisu.ts
  server/src/controllers/utils/course.ts
  server/src/routes/course.ts
  server/test/controllers/course.test.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/sisu.test.ts
  server/test/controllers/user.test.ts
Labels: frontend, backend

#471 Generate list of dependency licenses
  client/package-lock.json
  client/package.json
  client/public/javascript.html
Labels: documentation, frontend

#460 Edit grade form
  client/src/components/course-results-view/EditGradeDialog.tsx
  client/src/components/course-results-view/StudentGradeAccordion.tsx
  client/src/components/course-results-view/StudentGradeList.tsx
  client/src/components/course-results-view/StudentGradesDialog.tsx
  client/src/hooks/api/grade.ts
  client/src/tests/mock-data/mockFinalGrades.tsx
  common/types/grades.ts
  server/mock-data/attainment_grade.sql
  server/src/controllers/grades.ts
  server/src/routes/grades.ts
  server/test/controllers/grades.test.ts
Labels: frontend, backend

#473 Course language of instruction
  client/src/components/CourseView.tsx
  client/src/components/EditCourseView.tsx
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/tests/EditCourseView.test.tsx
  client/src/tests/mock-data/mockCourses.tsx
  client/src/tests/mock-data/mockInstancesWithStringDates.tsx
  client/src/tests/mock-data/mockSisuInstances.tsx
  client/src/types/index.ts
  common/types/course.ts
  common/types/language.ts
  server/mock-data/courses.sql
  server/src/controllers/course.ts
  server/src/controllers/grades.ts
  server/src/controllers/sisu.ts
  server/src/controllers/utils/course.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/course.ts
  server/src/routes/course.ts
  server/src/routes/grades.ts
  server/test/controllers/course.test.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/grades.test.ts
  server/test/controllers/sisu.test.ts
Labels: enhancement, frontend, backend, database

#472 Show multiple grades
  client/src/components/course-results-view/CourseResultsTableRow.tsx
  client/src/components/course-results-view/EditGradeDialog.tsx
  client/src/components/course-results-view/GradeOptionsDialog.tsx
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  client/src/components/course-results-view/StudentGradeAccordion.tsx
  client/src/components/course-results-view/StudentGradeList.tsx
  client/src/components/course-results-view/StudentGradesDialog.tsx
  client/src/utils/index.ts
  server/src/controllers/grades.ts
Labels: frontend

#476 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  .reuse/dep5
Labels: github

#478 Store previously created favicons to the project
  client/public/favicons/favicon-16x16.png
  client/public/favicons/favicon-16x16.png.license
  client/public/favicons/favicon-192x192.png
  client/public/favicons/favicon-192x192.png.license
  client/public/favicons/favicon-32x32.png
  client/public/favicons/favicon-32x32.png.license
  client/public/favicons/favicon-96x96.png
  client/public/favicons/favicon-96x96.png.license
Labels: frontend

#477 API for user data and UI data update
  client/src/components/course-results-view/CourseResultsTableRow.tsx
  client/src/components/course-results-view/GradeOptionsDialog.tsx
  client/src/tests/CourseResultsView.test.tsx
  client/src/tests/mock-data/mockFinalGrades.tsx
  client/src/tests/mock-data/mockGradeTree.tsx
  client/src/tests/mock-data/server.ts
  common/types/grades.ts
  common/types/user.ts
  server/src/controllers/grades.ts
  server/src/controllers/user.ts
  server/src/database/models/attainmentGrade.ts
  server/src/routes/grades.ts
  server/src/routes/user.ts
  server/test/controllers/grades.test.ts
  server/test/controllers/user.test.ts
Labels: enhancement, frontend, backend

#480 Date format in API and database
  common/types/course.ts
  common/types/general.ts
  common/types/grades.ts
  common/types/httpCode.ts
  common/types/index.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/date.ts
  server/src/database/migrations/00004-update-attainment-grade-dates-to-dateonly.ts
  server/src/database/models/attainmentGrade.ts
  server/src/database/models/courseInstance.ts
  server/src/routes/courseInstance.ts
  server/src/routes/grades.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/grades.test.ts
Labels: backend, database

#484 Sisu export flag
  client/src/App.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/components/course-results-view/CourseResultsTableRow.tsx
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  client/src/hooks/api/grade.ts
  common/types/grades.ts
  server/README.md
  server/mock-data/assessment_model.sql
  server/mock-data/attainment.sql
  server/mock-data/attainment_grade.sql
  server/package.json
  server/src/controllers/grades.ts
  server/src/database/migrations/00005-add-attainment-grade-sisu-flag.ts
  server/src/database/models/attainmentGrade.ts
  server/test/controllers/grades.test.ts
Labels: frontend, backend, database

#485 Attainment grading scale
  client/src/components/EditAttainmentView.tsx
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
  client/src/components/edit-attainment-view/LeafAttainment.tsx
  client/src/components/edit-attainment-view/SimpleDialog.tsx
  client/src/components/edit-attainment-view/StringTextField.tsx
  client/src/tests/CourseResultsView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/mock-data/mockAttainments.tsx
  common/types/attainment.ts
  common/types/formula.ts
  server/mock-data/attainment.sql
  server/mock-data/attainment_grade.sql
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/attainment.ts
  server/src/database/migrations/00006-add-max-grade-and-min-required-grade-to-attainments.ts
  server/src/database/models/attainment.ts
  server/src/formulas/manual.ts
  server/src/formulas/weightedAverage.ts
  server/src/routes/attainment.ts
  server/src/types/formulas.ts
  server/test/controllers/attainment.test.ts
  server/test/controllers/grades.test.ts
  server/test/formulas/weightedAverage.test.ts
  server/test/mock-data/attainment.ts
  server/test/mock-data/csv/grades_failing.csv
  server/test/mock-data/csv/grades_failing_non_manual.csv
  server/test/mock-data/csv/grades_over_max.csv
Labels: frontend, backend, database

#490 Shared ESLint config
  .eslintrc.json
  .github/workflows/pr-workflow.yaml
  .gitignore
  .reuse/dep5
  client/.eslintrc.json
  client/tsconfig.json
  common/package.json
  common/types/attainment.ts
  common/types/formula.ts
  common/types/grades.ts
  package-lock.json
  package.json
  server/.eslintrc.json
  server/tsconfig.json
Labels: enhancement

#495 Multiple sisu export CSV
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  server/src/routes/grades.ts
Labels: frontend

#498 union of the students of an instance and list of student numbers
  server/package-lock.json
  server/package.json
  server/src/controllers/grades.ts
  server/test/controllers/grades.test.ts
Labels: backend

#488 Grade expiry
  server/mock-data/assessment_model.sql
  server/mock-data/attainment.sql
  server/mock-data/attainment_grade.sql
  server/src/controllers/grades.ts
  server/src/controllers/utils/grades.ts
  server/test/controllers/grades.test.ts
  server/test/functions/gradeExpiry.test.ts
  server/test/functions/latestDate.test.ts
Labels: backend

#501 UI fixes
  client/src/components/CourseResultsView.tsx
  client/src/components/EditCourseView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/Footer.tsx
  client/src/components/NotFound.tsx
  client/src/components/alerts/AlertSnackbar.tsx
  client/src/components/alerts/UnsavedChangesDialog.tsx
  client/src/components/auth/ExternalAuth.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/PrivateRoute.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/UserButton.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course-results-view/EditGradeDialog.tsx
  client/src/components/course-results-view/FileErrorDialog.tsx
  client/src/components/course-results-view/FileLoadDialog.tsx
  client/src/components/course-results-view/MenuButton.tsx
  client/src/components/course-results-view/StudentGradesDialog.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
  client/src/components/edit-attainment-view/Attainment.tsx
  client/src/components/edit-attainment-view/ConfirmationDialog.tsx
  client/src/components/edit-attainment-view/LeafAttainment.tsx
  client/src/components/edit-attainment-view/ParentAttainment.tsx
  client/src/components/edit-attainment-view/SimpleDialog.tsx
  client/src/components/edit-formula-dialog/SelectFormula.tsx
  client/src/components/edit-formula-dialog/SetFormulaParams.tsx
  client/src/components/edit-formula-dialog/SubAttainment.tsx
  client/src/components/fetch-instances-view/FetchedInstances.tsx
  client/src/components/front-page/CourseTable.tsx
  client/src/components/typography/LightLabelBoldValue.tsx
  client/src/context/AuthProvider.tsx
  package-lock.json
Labels: bug, frontend

#502 LibreJS license list script
  .reuse/dep5
  client/license-exceptions.json
  client/package-lock.json
  client/package.json
  client/public/javascript.html
  client/set-web-labels.js
Labels: enhancement

#504 update server readme
  server/README.md
Labels: backend

#511 disable cache to always fetch latest attainment data
  client/src/components/EditAttainmentView.tsx
Labels: bug, frontend

#513 Initial configuration for Cypress E2E tests
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  e2e-tests/.eslintrc.json
  e2e-tests/.gitignore
  e2e-tests/Dockerfile
  e2e-tests/README.md
  e2e-tests/cypress.config.ts
  e2e-tests/cypress/e2e/placeholder.cy.ts
  e2e-tests/cypress/support/commands.ts
  e2e-tests/cypress/support/e2e.ts
  e2e-tests/docker-compose.yaml
  e2e-tests/package-lock.json
  e2e-tests/package.json
  e2e-tests/tsconfig.json
  e2e-tests/wait-for-frontend.sh
  robot-tests/README.md
  robot-tests/authentication/keywords.robot
  robot-tests/authentication/signUpAndSignIn.robot
  robot-tests/authentication/variables.robot
  robot-tests/common/keywords.robot
  robot-tests/common/variables.robot
  robot-tests/courses/assignments.robot
  robot-tests/courses/courseInstance.robot
  robot-tests/courses/createCourse.robot
  robot-tests/courses/keywords.robot
  robot-tests/courses/variables.robot
  robot-tests/run-tests.sh
  robot-tests/seccomp_profile.json
Labels: tests

#514 Cypress workflow in GitHub Actions and small fixes
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/pr-workflow.yaml
  client/set-web-labels.js
  client/src/tests/CourseResultsView.test.tsx
  e2e-tests/README.md
Labels: github, tests

#512 Creating two assessment models with the same name
  server/src/controllers/assessmentModel.ts
  server/src/database/migrations/00007-unique-course-level-assessment-model-name.ts
  server/src/routes/assessmentModel.ts
  server/test/controllers/assessmentModel.test.ts
Labels: bug, backend

#515 Update documentation
  README.md
  client/README.md
  client/build.sh
  client/package.json
  client/public/javascript.html
  common/README.md
  e2e-tests/README.md
  reuse-annotate.sh
  server/README.md
Labels: documentation

#518 Move client services to utils
  client/src/components/EditCourseView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/components/course-view/InstancesTable.tsx
  client/src/components/fetch-instances-view/FetchedInstances.tsx
  client/src/tests/sorting.test.tsx
  client/src/utils/sorting.ts
  client/src/utils/textFormat.ts
Labels: frontend

#519 Move Swagger documentation to YAML files
  server/docs/assessmentModel.yaml
  server/docs/attainment.yaml
  server/docs/auth.yaml
  server/docs/common.yaml
  server/docs/course.yaml
  server/docs/courseInstance.yaml
  server/docs/formula.yaml
  server/docs/grades.yaml
  server/docs/sisu.yaml
  server/docs/user.yaml
  server/src/routes/assessmentModel.ts
  server/src/routes/attainment.ts
  server/src/routes/auth.ts
  server/src/routes/course.ts
  server/src/routes/courseInstance.ts
  server/src/routes/formula.ts
  server/src/routes/grades.ts
  server/src/routes/index.ts
  server/src/routes/sisu.ts
  server/src/routes/user.ts
Labels: documentation, backend

#517 Csv grade upload dates
  client/src/components/course-results-view/FileLoadDialog.tsx
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  client/src/components/edit-formula-dialog/SelectFormula.tsx
  client/src/hooks/api/grade.ts
  server/docs/grades.yaml
  server/jest.config.js
  server/src/controllers/grades.ts
  server/src/database/migrations/00008-completion-expiry-date-constraint.ts
  server/src/database/models/attainmentGrade.ts
  server/src/types/grades.ts
  server/test/controllers/grades.test.ts
Labels: enhancement, frontend, backend, database

#489 Integer grades
  client/src/components/EditAttainmentView.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
  client/src/components/edit-attainment-view/SimpleDialog.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/mock-data/mockAttainments.tsx
  client/src/tests/mock-data/server.ts
  common/types/attainment.ts
  server/docs/attainment.yaml
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/attainment.ts
  server/src/database/migrations/00009-add-attainment-grade-type.ts
  server/src/database/models/attainment.ts
  server/src/types/grades.ts
  server/test/controllers/attainment.test.ts
  server/test/controllers/grades.test.ts
  server/test/mock-data/attainment.ts
  server/test/mock-data/csv/grades_incorrect_type.csv
Labels: enhancement, frontend, backend, database

#520 lint e2e
  .github/workflows/pr-workflow.yaml
  e2e-tests/cypress.config.ts
  e2e-tests/cypress/support/commands.ts
  e2e-tests/cypress/support/e2e.ts
Labels: github, tests

#521 Lint YAML
  .github/workflows/main-merge-workflow.yaml
  .github/workflows/pr-workflow.yaml
  .yamllint.yaml
  common-services.yaml
  docker-compose-from-images.yaml
  docker-compose.yaml
  e2e-tests/docker-compose.yaml
  server/docker-compose.yaml
  server/docs/assessmentModel.yaml
  server/docs/attainment.yaml
  server/docs/auth.yaml
  server/docs/common.yaml
  server/docs/course.yaml
  server/docs/courseInstance.yaml
  server/docs/formula.yaml
  server/docs/grades.yaml
  server/docs/sisu.yaml
  server/docs/user.yaml
Labels: github

#522 UI Updates/Fixes
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/edit-formula-dialog/EditFormulaDialog.tsx
  server/mock-data/teachers_in_charge.sql
Labels: frontend

#525 fix rounding
  server/src/controllers/grades.ts
Labels: backend

#526 update code comments
  server/src/app.ts
  server/src/controllers/user.ts
  server/src/controllers/utils/date.ts
  server/src/controllers/utils/grades.ts
  server/src/database/index.ts
  server/src/formulas/index.ts
  server/src/formulas/manual.ts
  server/src/formulas/weightedAverage.ts
  server/src/middleware/authorization.ts
  server/src/middleware/errorHandler.ts
  server/src/middleware/index.ts
  server/src/middleware/requestLogger.ts
  server/test/util/getCookies.ts
Labels: backend

#527 update child params on delete
  server/src/controllers/attainment.ts
Labels: backend
