Repository aalto-grades/aalto-grades, pull requests merged in 2023-01, with the labels that each got.

#111 Docker-compose with entrypoint
  .github/workflows/pr-workflow.yml
  docker-compose.yaml
  docker-tests/README.md
  docker-tests/docker-compose.yaml
  server/Dockerfile
  server/src/configs/database.ts
  server/src/database/migrations/00001-initial-migration.ts
Labels: backend, critical, database, github

#78 Retrieve teachers' courses from database
  client/src/services/courses.js
  docker-compose.yaml
  server/README.md
  server/mockdata/course_instances.sql
  server/mockdata/course_translations.sql
  server/package.json
  server/src/controllers/course.ts
  server/src/controllers/user.ts
  server/src/database/models/index.ts
  server/src/routes/index.ts
  server/src/services/course.ts
  server/src/services/index.ts
  server/test/routes/README.md
  server/test/routes/index.test.ts
  server/test/services/README.md
Labels: backend, database

#126 Fetch and parse course instance data from Sisu
  docker-compose.yaml
  server/.gitignore
  server/README.md
  server/package-lock.json
  server/package.json
  server/src/configs/config.ts
  server/src/configs/environment.ts
  server/src/controllers/course.ts
  server/src/routes/index.ts
  server/src/server.ts
  server/src/types/sisu.ts
  server/test/mockData/sisuMockData.ts
  server/test/routes/index.test.ts
Labels: backend

#34 Basic user management
  client/src/App.js
  client/src/components/auth/Login.js
  client/src/components/auth/LoginForm.js
  client/src/components/auth/PrivateRoute.js
  client/src/components/auth/Signup.js
  client/src/components/auth/SignupForm.js
  client/src/context/authProvider.js
  client/src/hooks/useAuth.js
  client/src/hooks/useLogout.js
  client/src/index.js
  client/src/services/axios.js
  client/src/services/user.js
  client/src/tests/Login.test.js
  client/src/tests/Signup.test.js
  docker-compose.yaml
  docker-tests/docker-compose.yaml
  package-lock.json
  server/mockdata/users.sql
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/configs/index.ts
  server/src/controllers/auth.ts
  server/src/routes/index.ts
  server/src/routes/login.ts
  server/test/routes/auth.test.ts
Labels: frontend, backend

#83 Ongoing instance component
  client/src/App.js
  client/src/components/CourseView.js
  client/src/components/course-view/Assignments.js
  client/src/components/course-view/InstanceTableHead.js
  client/src/components/course-view/InstanceTableRow.js
  client/src/components/course-view/InstancesTable.js
  client/src/components/course-view/OngoingInstanceInfo.js
  client/src/components/course-view/PartialAssignment.js
  client/src/services/sorting.js
  client/src/services/textFormat.js
  client/src/tests/CourseView.test.js
Labels: frontend

#112 Individual course and course instance route
  server/.gitignore
  server/jest.config.js
  server/package-lock.json
  server/src/controllers/course.ts
  server/src/controllers/user.ts
  server/src/database/models/courseAssignment.ts
  server/src/database/models/courseInstance.ts
  server/src/database/models/courseInstancePartialGrade.ts
  server/src/database/models/courseResult.ts
  server/src/database/models/courseRole.ts
  server/src/database/models/courseTranslation.ts
  server/src/database/models/userAssignmentGrade.ts
  server/src/database/models/userPartialGrade.ts
  server/src/routes/index.ts
  server/src/services/course.ts
  server/src/services/index.ts
  server/src/services/instance.ts
  server/src/services/user.ts
  server/test/app.test.ts
  server/test/routes/index.test.ts
Labels: backend, database

#116 Course instance creation
  server/src/controllers/course.ts
  server/src/routes/index.ts
  server/test/routes/index.test.ts
Labels: backend, database

#127 Implement route for creating a new course
  server/.eslintrc.json
  server/mockdata/course_instances.sql
  server/mockdata/courses.sql
  server/package-lock.json
  server/src/controllers/course.ts
  server/src/controllers/user.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00002-add-indexes.ts
  server/src/database/migrations/00003-add-constraints.ts
  server/src/database/models/course.ts
  server/src/database/models/courseInstance.ts
  server/src/routes/index.ts
  server/src/services/course.ts
  server/src/services/instance.ts
  server/test/controllers/course.test.ts
  server/test/routes/index.test.ts
Labels: backend, database

#129 Create instance - editing basic information
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/CourseView.js
  client/src/components/EditInstanceView.js
  client/src/components/FetchInstancesView.js
  client/src/components/FrontPage.js
  client/src/components/course-view/InstanceTableRow.js
  client/src/components/course-view/OngoingInstanceInfo.js
  client/src/components/course-view/PartialAssignment.js
  client/src/components/edit-instance-view/DateTextField.js
  client/src/components/edit-instance-view/DynamicTextFieldArray.js
  client/src/components/edit-instance-view/EditInstanceForm.js
  client/src/components/edit-instance-view/NumberTextField.js
  client/src/components/edit-instance-view/StringTextField.js
  client/src/components/fetch-instances-view/FetchedInstances.js
  client/src/components/typography/LightLabelBoldValue.js
  client/src/dummy-data/dummyInstances.js
  client/src/services/instances.js
  client/src/services/textFormat.js
  client/src/tests/CourseView.test.js
  client/src/tests/EditInstance.test.js
  client/src/tests/FetchInstances.test.js
  client/src/tests/sorting.test.js
Labels: frontend

#131 Frontend conditional rendering
  client/src/App.js
  client/src/components/CourseView.js
  client/src/components/FrontPage.js
  client/src/components/auth/PrivateRoute.js
  client/src/components/course-view/OngoingInstanceInfo.js
  client/src/tests/CourseView.test.js
  client/src/tests/FrontPage.test.js
Labels: frontend
