Repository aalto-grades/aalto-grades, pull requests merged in 2023-07, with the labels that each got.

#328 Get root attainment of an assessment model
  server/mock-data/assessment_model.sql
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/controllers/utils/attainment.ts
  server/src/routes/attainment.ts
  server/test/controllers/attainment.test.ts
Labels: backend

#317 Assessment model creation from client
  client/.eslintrc.json
  client/src/App.tsx
  client/src/components/AddAttainmentsView.tsx
  client/src/components/CourseView.tsx
  client/src/components/CreateAttainmentView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/InstanceSummaryView.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/components/course-view/CreateAssessmentModelDialog.tsx
  client/src/components/create-attainment/Attainment.tsx
  client/src/components/create-attainment/ConfirmationDialog.tsx
  client/src/components/create-attainment/DateTextField.tsx
  client/src/components/create-attainment/LeafAttainment.tsx
  client/src/components/create-attainment/ParentAttainment.tsx
  client/src/components/create-attainment/SimpleDialog.tsx
  client/src/components/create-attainment/StringTextField.tsx
  client/src/components/create-course-view/CreateCourseForm.tsx
  client/src/components/create-course-view/TextFieldBox.tsx
  client/src/services/assessmentModels.tsx
  client/src/services/attainments.tsx
  client/src/tests/AddAttainmentsView.test.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/CreateAttainmentView.test.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
  client/src/tests/Login.test.tsx
  client/src/tests/mock-data/mockAttainments.tsx
  client/src/tests/mock-data/mockAttainmentsClient.tsx
  client/src/tests/mock-data/mockAttainmentsServer.tsx
  client/src/types/index.tsx
  common/types/attainment.ts
  server/src/controllers/attainment.ts
  server/test/controllers/attainment.test.ts
Labels: frontend

#329 Remove unused weighted average params
  server/mock-data/attainment.sql
  server/src/formulas/index.ts
  server/src/formulas/weightedAverage.ts
  server/test/formulas/weightedAverage.test.ts
Labels: backend

#324 Update/remove mockdata from course creation view
  client/package-lock.json
  client/package.json
  client/src/components/CreateCourseView.tsx
  client/src/components/alerts/AlertSnackbar.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/create-course-view/CreateCourseForm.tsx
  client/src/components/create-course-view/TextFieldBox.tsx
  client/src/tests/CreateCourse.test.tsx
  client/src/types/index.tsx
  common/types/course.ts
  common/types/user.ts
  server/src/controllers/course.ts
  server/src/routes/course.ts
  server/test/controllers/course.test.ts
Labels: frontend, backend

#330 Update attainment grades and remove course result
  server/mock-data/course_result.sql
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/controllers/user.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00002-add-indexes.ts
  server/src/database/models/attainmentGrade.ts
  server/src/database/models/courseResult.ts
  server/src/database/models/index.ts
  server/src/database/seeders/001-dummy-data.ts
  server/test/controllers/grades.test.ts
Labels: database

#335 Display attainment formula from backend, remove mock data and functions
  client/.eslintrc.json
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/create-attainment/ParentAttainment.tsx
  client/src/context/FormulaSelectionRoute.tsx
  client/src/services/assessmentModels.tsx
  client/src/services/attainments.tsx
  client/src/services/formulas.tsx
  client/src/tests/CourseView.test.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/FormulaAttributesView.test.tsx
  client/src/tests/SelectFormulaView.test.tsx
  client/src/tests/mock-data/mockAttainments.tsx
  client/src/tests/mock-data/mockAttainmentsClient.tsx
  client/src/tests/mock-data/mockFormulas.tsx
  common/types/attainment.ts
  server/src/controllers/attainment.ts
  server/src/controllers/utils/attainment.ts
  server/src/formulas/manual.ts
  server/src/formulas/weightedAverage.ts
  server/src/routes/attainment.ts
  server/test/controllers/attainment.test.ts
  server/test/mock-data/attainment.ts
Labels: frontend, backend

#334 Update course instance creation from client
  client/src/App.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/InstanceSummaryView.tsx
  client/src/components/alerts/UnsavedChangesDialog.tsx
  client/src/components/course-view/InstancesTable.tsx
  client/src/components/create-course-view/CreateCourseForm.tsx
  client/src/components/edit-instance-view/DateTextField.tsx
  client/src/components/edit-instance-view/DynamicTextFieldArray.tsx
  client/src/components/edit-instance-view/EditInstanceForm.tsx
  client/src/components/edit-instance-view/NumberTextField.tsx
  client/src/components/edit-instance-view/StringTextField.tsx
  client/src/components/fetch-instances-view/FetchedInstances.tsx
  client/src/context/InstanceCreationRoute.tsx
  client/src/services/textFormat.tsx
  client/src/tests/CreateCourse.test.tsx
  client/src/tests/EditInstance.test.tsx
  client/src/tests/InstanceSummaryView.test.tsx
  client/src/tests/mock-data/mockSisuInstances.tsx
  common/types/course.ts
Labels: frontend

#339 Set formulas and params from API
  common/types/attainment.ts
  server/src/controllers/attainment.ts
  server/src/controllers/formula.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/attainment.ts
  server/src/formulas/index.ts
  server/src/formulas/manual.ts
  server/test/controllers/attainment.test.ts
  server/test/mock-data/attainment.ts
Labels: backend

#344 Restrict instance and assessment model creation rights
  server/src/controllers/assessmentModel.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/utils/user.ts
  server/src/routes/course.ts
  server/test/controllers/assessmentModel.test.ts
  server/test/controllers/course.test.ts
  server/test/controllers/courseInstance.test.ts
Labels: backend

#346 Restrict grade creation/add/export rights
  server/src/controllers/assessmentModel.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/user.ts
  server/src/routes/grades.ts
  server/test/controllers/assessmentModel.test.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/grades.test.ts
  server/test/mock-data/misc.ts
Labels: backend

#345 Change formula parameter format
  common/types/attainment.ts
  common/types/grades.ts
  common/types/index.ts
  server/mock-data/attainment.sql
  server/package-lock.json
  server/package.json
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/assessmentModel.ts
  server/src/controllers/utils/attainment.ts
  server/src/controllers/utils/courseInstance.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/attainment.ts
  server/src/formulas/index.ts
  server/src/formulas/manual.ts
  server/src/formulas/weightedAverage.ts
  server/src/types/formulas.ts
  server/src/types/grades.ts
  server/src/types/language.ts
  server/test/controllers/attainment.test.ts
  server/test/controllers/grades.test.ts
  server/test/formulas/weightedAverage.test.ts
  server/test/functions/csvParsing.test.ts
  server/test/mock-data/attainment.ts
Labels: backend, database

#353 Frontend footer
  client/public/favicon.ico
  client/public/favicon.ico.license
  client/src/App.tsx
  client/src/components/Footer.tsx
Labels: enhancement, frontend

#354 Prohibit creating multiple root attainments
  server/mock-data/assessment_model.sql
  server/src/configs/environment.ts
  server/src/controllers/attainment.ts
  server/src/database/seeders/001-dummy-data.ts
  server/test/controllers/attainment.test.ts
Labels: backend, database

#361 Reorder routes and controllers according to method
  server/src/controllers/attainment.ts
  server/src/controllers/auth.ts
  server/src/controllers/grades.ts
  server/src/routes/attainment.ts
  server/src/routes/auth.ts
  server/src/routes/grades.ts
  server/test/controllers/attainment.test.ts
  server/test/controllers/auth.test.ts
  server/test/controllers/grades.test.ts
Labels: backend

#363 Fix course view attainments incorrectly showing subattainments exist
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/attainments/CustomAccordion.tsx
Labels: bug, frontend

#350 Update course results view
  client/src/App.tsx
  client/src/components/CourseResultsView.tsx
  client/src/components/CourseView.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/components/course-results-view/SisuExportDialog.tsx
  client/src/components/course-view/FileLoadDialog.tsx
  client/src/services/grades.tsx
  client/src/tests/CourseResultsView.test.tsx
  client/src/tests/mock-data/mockFinalGrades.tsx
  common/types/grades.ts
  server/mock-data/assessment_model.sql
  server/mock-data/attainment.sql
  server/mock-data/attainment_grade.sql
  server/src/controllers/grades.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/models/attainmentGrade.ts
  server/src/routes/grades.ts
  server/src/routes/index.ts
  server/test/controllers/grades.test.ts
Labels: frontend, backend, database

#366 Attempting to add course instance with an existing Sisu instance ID
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/edit-instance-view/EditInstanceForm.tsx
  client/src/components/fetch-instances-view/FetchedInstances.tsx
  common/types/course.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/sisu.ts
  server/src/routes/courseInstance.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/sisu.test.ts
Labels: bug, enhancement, frontend, backend

#389 Not found page
  client/src/App.tsx
  client/src/components/CourseResultsView.tsx
  client/src/components/CourseView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/FrontPage.tsx
  client/src/components/NotFound.tsx
  client/src/components/course-results-view/SisuExportDialog.tsx
  client/src/tests/NotFound.test.tsx
  server/src/controllers/utils/attainment.ts
  server/test/controllers/attainment.test.ts
Labels: enhancement, frontend, backend

#383 Keep formula param children tags and subattainment tags in sync
  server/mock-data/assessment_model.sql
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/formulas/weightedAverage.ts
  server/src/types/formulas.ts
  server/test/controllers/attainment.test.ts
Labels: backend

#391 Update API return value format
  client/src/hooks/api/assessmentModel.ts
  client/src/hooks/api/attainment.ts
  client/src/hooks/api/course.ts
  client/src/hooks/api/formula.ts
  client/src/hooks/api/grade.ts
  client/src/hooks/api/instance.ts
  client/src/hooks/api/user.ts
  client/src/tests/CourseView.test.tsx
  client/src/tests/CreateCourse.test.tsx
  client/src/tests/EditAttainmentView.test.tsx
  client/src/tests/mock-data/server.ts
  server/src/controllers/assessmentModel.ts
  server/src/controllers/attainment.ts
  server/src/controllers/auth.ts
  server/src/controllers/course.ts
  server/src/controllers/courseInstance.ts
  server/src/controllers/formula.ts
  server/src/controllers/grades.ts
  server/src/controllers/sisu.ts
  server/src/controllers/user.ts
  server/src/routes/assessmentModel.ts
  server/src/routes/attainment.ts
  server/src/routes/auth.ts
  server/src/routes/course.ts
  server/src/routes/courseInstance.ts
  server/src/routes/formula.ts
  server/src/routes/grades.ts
  server/src/routes/index.ts
  server/src/routes/sisu.ts
  server/src/routes/user.ts
  server/test/controllers/assessmentModel.test.ts
  server/test/controllers/attainment.test.ts
  server/test/controllers/auth.test.ts
  server/test/controllers/course.test.ts
  server/test/controllers/courseInstance.test.ts
  server/test/controllers/formula.test.ts
  server/test/controllers/grades.test.ts
  server/test/controllers/sisu.test.ts
  server/test/controllers/user.test.ts
Labels: frontend, backend

#394 Remove "import grades" button from course view
  client/src/components/CourseView.tsx
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/FileErrorDialog.tsx
  client/src/components/course-results-view/FileLoadDialog.tsx
  client/src/components/course-results-view/MenuButton.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/tests/FileLoadDialog.test.tsx
Labels: frontend

#395 Rename import to upload and export to download
  client/src/components/course-results-view/CourseResultTableToolbar.tsx
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  client/src/tests/CourseResultsView.test.tsx
  client/src/tests/FileLoadDialog.test.tsx
Labels: frontend

#393 Basic LibreJS compatibility
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/javascript.html
  client/set-web-labels.js
  client/src/components/Footer.tsx
Labels: frontend

#398 Formula editing improvements
  client/package-lock.json
  client/package.json
  client/src/components/CreateCourseView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/alerts/UnsavedChangesDialog.tsx
  client/src/components/edit-formula-dialog/EditFormulaDialog.tsx
  client/src/components/edit-formula-dialog/FormulaSummary.tsx
  client/src/components/edit-formula-dialog/SelectFormula.tsx
  client/src/components/edit-formula-dialog/SetFormulaParams.tsx
  client/src/components/edit-formula-dialog/SubAttainment.tsx
  client/src/components/edit-formula-dialog/ViewFormulaAccordion.tsx
  client/src/utils/index.ts
  common/types/formula.ts
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/formulas/weightedAverage.ts
  server/src/types/formulas.ts
  server/test/controllers/attainment.test.ts
  server/test/formulas/weightedAverage.test.ts
  server/test/mock-data/attainment.ts
Labels: frontend, backend

#402 Display formula params in attainments and update param logic
  client/.eslintrc.json
  client/src/App.tsx
  client/src/components/CourseView.tsx
  client/src/components/CreateCourseView.tsx
  client/src/components/EditAttainmentView.tsx
  client/src/components/EditInstanceView.tsx
  client/src/components/FetchInstancesView.tsx
  client/src/components/FrontPage.tsx
  client/src/components/alerts/AlertSnackbar.tsx
  client/src/components/attainments/AttainmentCategory.tsx
  client/src/components/attainments/CustomAccordion.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/CourseResultsTableHead.tsx
  client/src/components/course-results-view/FileLoadDialog.tsx
  client/src/components/course-results-view/MenuButton.tsx
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  client/src/components/course-view/Attainments.tsx
  client/src/components/course-view/CourseDetails.tsx
  client/src/components/course-view/InstancesTable.tsx
  client/src/components/edit-attainment-view/Attainment.tsx
  client/src/components/edit-attainment-view/ConfirmationDialog.tsx
  client/src/components/edit-attainment-view/LeafAttainment.tsx
  client/src/components/edit-attainment-view/ParentAttainment.tsx
  client/src/components/edit-attainment-view/SimpleDialog.tsx
  client/src/components/edit-attainment-view/StringTextField.tsx
  client/src/components/edit-formula-dialog/EditFormulaDialog.tsx
  client/src/components/front-page/CourseTable.tsx
  client/src/tests/EditAttainmentView.test.tsx
  common/types/attainment.ts
  common/types/formula.ts
  common/types/grades.ts
  common/types/user.ts
  server/.eslintrc.json
  server/mock-data/attainment.sql
  server/src/controllers/attainment.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/attainment.ts
  server/src/formulas/index.ts
  server/src/formulas/manual.ts
  server/src/formulas/weightedAverage.ts
  server/src/middleware/errorHandler.ts
  server/src/types/formulas.ts
  server/src/types/model.ts
  server/src/types/sisu.ts
  server/test/controllers/attainment.test.ts
  server/test/util/getCookies.ts
Labels: frontend
