Repository aalto-grades/aalto-grades, pull requests merged in 2024-05, with the labels that each got.

#701 Use best final grade instead of the latest one
  client/src/components/course-results-view/EditFinalGradesDialog.tsx
  client/src/components/course-results-view/FinalGradeCell.tsx
  client/src/context/GradesTableProvider.tsx
  client/src/utils/index.ts
  server/src/controllers/grades.ts
  server/test/controllers/grades.test.ts
Labels: frontend, backend

#706 Force unique course code
  server/docs/attainment.yaml
  server/docs/course.yaml
  server/mock-data/courses.sql
  server/src/controllers/attainment.ts
  server/src/controllers/course.ts
  server/src/database/migrations/00009-add-course-code-unique.ts
  server/test/controllers/course.test.ts
Labels: backend, database

#705 Add warning when using latest grades
  client/src/components/course-results-view/CalculateFinalGradesDialog.tsx
Labels: frontend

#702 Prevent invalid final grades
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course-view/EditCourseView.tsx
  client/src/components/front-page/CreateCourseDialog.tsx
  server/src/controllers/course.ts
  server/src/controllers/finalGrades.ts
  server/test/controllers/course.test.ts
  server/test/controllers/finalGrades.test.ts
Labels: bug, frontend, backend

#707 Allow teacher to edit assistants
  client/src/App.tsx
  client/src/components/course-view/EditCourseView.tsx
  client/src/components/course-view/SideMenu.tsx
  client/src/components/front-page/CreateCourseDialog.tsx
  server/src/controllers/course.ts
  server/src/controllers/utils/course.ts
  server/src/database/migrations/00010-remove-course-role-uniqueness.ts
  server/src/database/models/courseRole.ts
  server/src/routes/course.ts
  server/test/controllers/course.test.ts
Labels: enhancement, question, frontend, backend

#710 Add support for second national language grading scale
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course-results-view/FinalGradeCell.tsx
  client/src/components/course-results-view/PredictedGradeCell.tsx
  client/src/utils/textFormat.ts
  server/src/controllers/finalGrades.ts
  server/src/controllers/grades.ts
  server/test/controllers/finalGrades.test.ts
  server/test/controllers/grades.test.ts
Labels: frontend, backend

#715 404 when user has no A+ staff courses
  server/docs/aplus.yaml
  server/src/controllers/aplus.ts
  server/test/controllers/aplus.test.ts
Labels: backend, integration

#680 Create attainments from A+ sources
  client/src/components/course-view/AplusTokenDialog.tsx
  client/src/components/course-view/AttainmentsView.tsx
  client/src/components/course-view/CreateAplusAttainments.tsx
  client/src/components/course-view/NewAplusAttainmentsDialog.tsx
  client/src/components/course-view/SelectAplusCourse.tsx
  client/src/components/course-view/SelectAplusGradeSources.tsx
  client/src/hooks/api/aplus.ts
  client/src/hooks/useApi.ts
  common/types/aplus.ts
Labels: frontend, integration
