Repository aalto-grades/aalto-grades, pull requests merged in 2024-06, with the labels that each got.

#716 A+ token
  client/src/components/auth/UserButton.tsx
  client/src/components/course-view/AplusTokenDialog.tsx
  client/src/components/course-view/CoursePartsView.tsx
  client/src/components/course-view/NewAplusGradePartsDialog.tsx
  client/src/components/shared/AplusTokenDialog.tsx
  client/src/hooks/api/aplus.ts
  client/src/utils/utils.ts
  server/docs/aplus.yaml
  server/docs/common.yaml
  server/src/controllers/aplus.ts
  server/src/controllers/utils/aplus.ts
  server/test/controllers/aplus.test.ts
  server/test/util/responses.ts
Labels: frontend, backend, integration

#727 View student grades
  client/src/App.tsx
  client/src/components/FrontPage.tsx
  client/src/components/StudentsView.tsx
  client/src/hooks/api/user.ts
  common/types/course.ts
  common/types/user.ts
  server/docs/course.yaml
  server/docs/user.yaml
  server/src/controllers/grades.ts
  server/src/controllers/user.ts
  server/src/controllers/utils/user.ts
  server/src/database/models/courseRole.ts
  server/src/middleware/authorization.ts
  server/src/routes/user.ts
  server/test/controllers/user.test.ts
  server/test/util/createData.ts
Labels: enhancement, frontend, backend

#733 Add A+ source info
  client/src/components/course-view/SelectAplusGradeSources.tsx
  common/types/aplus.ts
  server/docs/aplus.yaml
  server/src/controllers/aplus.ts
  server/src/database/migrations/00013-add-aplus-grade-source-info.ts
  server/src/database/models/aplusGradeSource.ts
  server/test/controllers/aplus.test.ts
  server/test/util/createData.ts
Labels: frontend, backend, integration

#729 Show A+ grade sources of course parts
  client/src/components/course-view/CoursePartsView.tsx
  client/src/components/course-view/ViewAplusGradeSourcesDialog.tsx
  client/src/hooks/api/aplus.ts
  client/src/tests/mock-data/mockCourseParts.ts
  common/package-lock.json
  common/types/coursePart.ts
  server/docs/coursePart.yaml
  server/package-lock.json
  server/src/controllers/utils/coursePart.ts
  server/test/util/createData.ts
Labels: frontend, backend, integration

#734 A+ source ID in grades
  client/src/tests/mock-data/mockGrades.ts
  common/types/grades.ts
  server/docs/aplus.yaml
  server/docs/grades.yaml
  server/src/controllers/aplus.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/aplus.ts
  server/src/database/migrations/00014-add-aplus-grade-source-id-to-grades.ts
  server/src/database/models/attainmentGrade.ts
  server/src/types/dbNewDataTypes.ts
  server/test/controllers/aplus.test.ts
  server/test/controllers/grades.test.ts
  server/test/util/createData.ts
Labels: backend, integration

#737 Warn teacher if editing model with final grades
  client/src/components/alerts/SaveConfirmDialog.tsx
  client/src/components/course-view/ModelsView.tsx
  client/src/components/graph/Graph.tsx
Labels: frontend

#740 A+ grade fetching update
  server/src/controllers/aplus.ts
  server/test/controllers/aplus.test.ts
Labels: backend, integration

#738 Fix inconsistencies with Title Case
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/FrontPage.tsx
  client/src/components/NotFound.tsx
  client/src/components/StudentsView.tsx
  client/src/components/alerts/UnsavedChangesDialog.tsx
  client/src/components/auth/ExternalAuth.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/UserButton.tsx
  client/src/components/course-results-view/CalculateFinalGradesDialog.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course-results-view/EditFinalGradesDialog.tsx
  client/src/components/course-results-view/EditGradesDialog.tsx
  client/src/components/course-results-view/SisuDownloadDialog.tsx
  client/src/components/course-results-view/UserGraphDialog.tsx
  client/src/components/course-view/CoursePartsView.tsx
  client/src/components/course-view/CreateGradingModelDialog.tsx
  client/src/components/course-view/EditCourseView.tsx
  client/src/components/course-view/EditGradingModelDialog.tsx
  client/src/components/course-view/ModelsView.tsx
  client/src/components/course-view/SideMenu.tsx
  client/src/components/course-view/UploadDialog.tsx
  client/src/components/course-view/UploadDialogConfirm.tsx
  client/src/components/course-view/UploadDialogMismatchDialog.tsx
  client/src/components/course-view/UploadDialogUpload.tsx
  client/src/components/course-view/ViewAplusGradeSourcesDialog.tsx
  client/src/components/front-page/CourseTable.tsx
  client/src/components/front-page/CreateCourseDialog.tsx
  client/src/components/front-page/users-view/AddUserDialog.tsx
  client/src/components/front-page/users-view/UsersTable.tsx
  client/src/components/front-page/users-view/UsersView.tsx
  client/src/components/graph/AdditionNode.tsx
  client/src/components/graph/AverageNode.tsx
  client/src/components/graph/CoursePartValuesDialog.tsx
  client/src/components/graph/Graph.tsx
  client/src/components/graph/MaxNode.tsx
  client/src/components/graph/RequireNode.tsx
  client/src/components/graph/SelectCoursePartsDialog.tsx
  client/src/components/graph/StepperNode.tsx
  client/src/components/graph/SubstituteNode.tsx
  client/src/components/shared/AplusTokenDialog.tsx
  client/src/components/shared/SaveBar.tsx
  client/src/context/GradesTableProvider.tsx
  client/src/hooks/useAuth.ts
  client/src/tests/CourseResultsView.test.tsx
  client/src/tests/EditCourseView.test.tsx
  client/src/tests/Login.test.tsx
  client/src/tests/NotFound.test.tsx
  client/src/tests/mock-data/mockCourse.ts
  client/src/tests/mock-data/mockGradingModel.ts
  common/util/calculateGraph.ts
  common/util/initGraph.ts
  e2e-tests/tests/assistant.spec.ts
  e2e-tests/tests/teacher.spec.ts
  e2e-tests/tests/test.spec.ts
  server/src/configs/swagger.ts
  server/test/controllers/gradingModel.test.ts
  server/test/util/responses.ts
Labels: question, frontend, design

#750 Don't show warning if calling self info fails with 401
  client/src/hooks/api/auth.ts
Labels: bug, frontend

#749 Add deleting student data
  client/src/App.tsx
  client/src/components/ManageStudentsView.tsx
  client/src/components/StudentsView.tsx
  client/src/components/front-page/users-view/UsersView.tsx
  client/src/hooks/api/grade.ts
  client/src/hooks/api/user.ts
  common/types/grades.ts
  common/types/user.ts
  server/docs/grades.yaml
  server/docs/user.yaml
  server/src/controllers/grades.ts
  server/src/controllers/user.ts
  server/src/database/migrations/00015-change-attainment-grade-constraint.ts
  server/src/database/models/attainmentGrade.ts
  server/src/routes/grades.ts
  server/src/routes/user.ts
  server/test/controllers/grades.test.ts
  server/test/controllers/user.test.ts
Labels: enhancement, frontend, backend
