Repository aalto-grades/aalto-grades, pull requests merged in 2024-07, with the labels that each got.

#753 Course list pagination
  client/Dockerfile
  client/Dockerfile.prod
  client/src/components/FrontPage.tsx
  client/src/components/auth/UserButton.tsx
  client/src/components/front-page/CourseTable.tsx
  client/src/components/front-page/users-view/UsersTable.tsx
  client/src/components/front-page/users-view/UsersView.tsx
  e2e-tests/tests/admin.spec.ts
  server/docs/auth.yaml
  server/src/routes/auth.ts
  server/test/controllers/auth.test.ts
  server/test/util/createData.ts
Labels: enhancement, frontend, backend

#745 A+ import frontend
  client/src/components/course-view/AplusImportDialog.tsx
  client/src/components/course-view/UploadDialog.tsx
  client/src/components/course-view/UploadDialogUpload.tsx
  client/src/hooks/api/aplus.ts
  server/src/controllers/aplus.ts
Labels: frontend, integration

#735 Improve logging
  .gitignore
  .yamllint.yaml
  SECURITY.md
  client/.gitignore
  client/Dockerfile
  client/Dockerfile.prod
  docker-compose-from-images-dev.yaml
  docker-compose-from-images.yaml
  reverse-proxy/Dockerfile
  server/.gitignore
  server/docs/logging.md
  server/src/app.ts
  server/src/configs/environment.ts
  server/src/configs/winston.ts
  server/src/controllers/aplus.ts
  server/src/controllers/auth.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/aplus.ts
  server/src/controllers/utils/auth.ts
  server/src/controllers/utils/course.ts
  server/src/controllers/utils/grades.ts
  server/src/database/index.ts
  server/src/database/migrations/00001-initial-migration.ts
  server/src/database/migrations/00002-add-indexes.ts
  server/src/database/migrations/00003-add-constraints.ts
  server/src/database/migrations/00004-add-comment-to-fgrade.ts
  server/src/database/migrations/00005-add-archiving.ts
  server/src/database/migrations/00006-add-aplus-grade-source.ts
  server/src/database/migrations/00007-add-manual-final-grade.ts
  server/src/database/migrations/00008-add-attainment-name-unique.ts
  server/src/database/migrations/00009-add-course-code-unique.ts
  server/src/database/migrations/00010-remove-course-role-uniqueness.ts
  server/src/database/migrations/00011-rename-assessment-model.ts
  server/src/database/migrations/00012-rename-attainment.ts
  server/src/database/migrations/00013-add-aplus-grade-source-info.ts
  server/src/database/seeders/001-dummy-data.ts
  server/src/middleware/errorHandler.ts
  server/src/middleware/requestLogger.ts
  server/src/routes/auth.ts
  server/src/server.ts
  server/src/types/aPlus.ts
  server/src/types/index.ts
  server/test/controllers/grades.test.ts
  ssh.config
Labels: documentation, backend, security

#762 Improve production
  .gitignore
  common-services.yaml
  docker-compose-from-images-dev.yaml
  docker-compose-from-images.yaml
  reverse-proxy/Dockerfile
  reverse-proxy/reverse-proxy.conf
  server/dockerfiles/Dockerfile.prod.run
  server/dockerfiles/Dockerfile.prod.run.dev
  server/docs/logging.md
  server/src/configs/environment.ts
  server/src/controllers/auth.ts
  server/src/controllers/utils/saml.ts
  server/src/server.ts
Labels: backend

#758 Try to fix jest github output
  .github/workflows/dev-push-workflow.yaml
  .github/workflows/pr-workflow.yaml
  server/dockerfiles/Dockerfile.test
  server/jest.config.ts
  server/package.json
Labels: bug, enhancement, backend, github, tests

#754 A+ exercise grade source
  client/src/components/course-view/SelectAplusGradeSources.tsx
  client/src/components/course-view/ViewAplusGradeSourcesDialog.tsx
  common/types/aplus.ts
  server/docs/aplus.yaml
  server/docs/coursePart.yaml
  server/src/controllers/aplus.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/coursePart.ts
  server/src/database/migrations/00017-add-aplus-exercises-as-grade-sources.ts
  server/src/database/models/aplusGradeSource.ts
  server/src/types/aPlus.ts
  server/src/types/aplus.ts
  server/src/types/index.ts
  server/test/controllers/aplus.test.ts
  server/test/util/createData.ts
Labels: frontend, backend, database, integration

#767 A+ grade source management
  client/src/components/course-view/AddAplusGradeSourceDialog.tsx
  client/src/components/course-view/CoursePartsView.tsx
  client/src/components/course-view/CreateAplusCourseParts.tsx
  client/src/components/course-view/NewAplusCoursePartsDialog.tsx
  client/src/components/course-view/SelectAplusGradeSource.tsx
  client/src/components/course-view/SelectAplusGradeSources.tsx
  client/src/components/course-view/ViewAplusGradeSourcesDialog.tsx
  client/src/hooks/api/aplus.ts
  common/types/aplus.ts
  server/docs/aplus.yaml
  server/docs/common.yaml
  server/docs/coursePart.yaml
  server/src/controllers/aplus.ts
  server/src/controllers/grades.ts
  server/src/controllers/utils/aplus.ts
  server/src/controllers/utils/coursePart.ts
  server/src/routes/aplus.ts
  server/test/controllers/aplus.test.ts
  server/test/util/createData.ts
Labels: frontend, backend, integration

#771 One grade per A+ grade source and user
  server/src/controllers/grades.ts
  server/test/controllers/grades.test.ts
Labels: backend

#774 Don't allow adding the same A+ grade source twice from the client
  client/src/components/course-view/AddAplusGradeSourceDialog.tsx
  client/src/components/course-view/CoursePartsView.tsx
  client/src/components/course-view/SelectAplusGradeSource.tsx
  client/src/components/course-view/SelectAplusGradeSources.tsx
  client/src/utils/utils.ts
  common/util/aplus.ts
  server/src/controllers/aplus.ts
Labels: frontend, backend

#769 LibreJS plugin
  client/Dockerfile
  client/Dockerfile.prod
  client/build.sh
  client/libreJsPlugin.ts
  client/license-exceptions.json
  client/package-lock.json
  client/package.json
  client/public/javascript.html
  client/set-web-labels.cjs
  client/tsconfig.json
  client/vite.config.ts
Labels: enhancement, frontend

#776 Resolve TODOs
  client/src/components/course-view/AddAplusGradeSourceDialog.tsx
  client/src/components/course-view/CreateAplusCourseParts.tsx
  client/src/components/course-view/NewAplusCoursePartsDialog.tsx
  client/src/components/course-view/SelectAplusCourse.tsx
  client/src/components/course-view/SelectAplusGradeSources.tsx
  common/types/aplus.ts
  server/docs/aplus.yaml
  server/src/controllers/aplus.ts
  server/src/controllers/utils/aplus.ts
  server/test/controllers/aplus.test.ts
Labels: frontend, backend

#778 Department drop-down
  client/src/components/course-view/EditCourseView.tsx
  client/src/components/front-page/CreateCourseDialog.tsx
  client/src/utils/utils.ts
  e2e-tests/tests/admin.spec.ts
Labels: frontend

#780 Small fixes
  client/public/Import-grades-file-example.jpg
  client/public/Import-grades-file-example.jpg.license
  client/public/index.html
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course-view/CoursePartsView.tsx
  client/src/components/graph/RequireNode.tsx
  client/src/components/graph/SubstituteNode.tsx
Labels: bug, frontend

#782 Add graph node tooltips
  client/src/components/graph/Graph.tsx
Labels: enhancement, frontend

#770 Grade dates from A+
  client/src/components/course-view/SelectAplusGradeSource.tsx
  client/src/components/course-view/SelectAplusGradeSources.tsx
  client/src/utils/utils.ts
  common/types/aplus.ts
  server/docs/aplus.yaml
  server/src/controllers/aplus.ts
  server/src/database/migrations/00018-add-date-to-aplus-grade-source.ts
  server/src/database/models/aplusGradeSource.ts
  server/src/types/aplus.ts
  server/test/controllers/aplus.test.ts
  server/test/util/createData.ts
Labels: backend, integration

#786 Fix backend test workflows
  .github/workflows/dev-push-workflow.yaml
  .github/workflows/pr-workflow.yaml
Labels: bug, backend, github, tests

#789 Fetch grades from multiple A+ sources
  server/src/controllers/aplus.ts
  server/test/controllers/aplus.test.ts
Labels: backend, integration

#784 Add confirm modal
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ManageStudentsView.tsx
  client/src/components/alerts/ConfirmDialog.tsx
  client/src/components/alerts/SaveConfirmDialog.tsx
  client/src/components/alerts/UnsavedChangesDialog.tsx
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course-results-view/EditFinalGradesDialog.tsx
  client/src/components/course-results-view/EditGradesDialog.tsx
  client/src/components/course-view/CoursePartsView.tsx
  client/src/components/course-view/EditCourseView.tsx
  client/src/components/course-view/ModelsView.tsx
  client/src/components/front-page/CreateCourseDialog.tsx
  client/src/components/front-page/users-view/AddUserDialog.tsx
  client/src/components/front-page/users-view/DeleteUserDialog.tsx
  client/src/components/front-page/users-view/UsersTable.tsx
  client/src/components/graph/Graph.tsx
Labels: enhancement, frontend

#792 Allow deleting course parts with A+ sources
  server/src/database/migrations/00019-change-aplus-grade-source-constraint.ts
  server/src/database/models/aplusGradeSource.ts
Labels: bug, database

#791 Show date of A+ sources in frontend
  client/src/components/course-view/ViewAplusGradeSourcesDialog.tsx
  common/types/aplus.ts
  server/docs/aplus.yaml
  server/src/controllers/aplus.ts
  server/src/controllers/utils/aplus.ts
Labels: frontend, backend

#795 Display version number
  client/Dockerfile
  client/Dockerfile.prod
  client/package.json
  client/src/components/Footer.tsx
  client/tsconfig.json
  client/vite-env.d.ts
  client/vite.config.ts
  docker-compose-from-images-dev.yaml
  docker-compose-from-images.yaml
  package.json
  server/package.json
Labels: frontend

#793 Max grade
  client/src/components/StyledDataGrid.tsx
  client/src/components/course-results-view/CalculateFinalGradesDialog.tsx
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course-results-view/EditGradesDialog.tsx
  client/src/components/course-results-view/GradeCell.tsx
  client/src/components/course-view/CoursePartsView.tsx
  client/src/components/course-view/NewAplusCoursePartsDialog.tsx
  client/src/components/course-view/NewCoursePartDialog.tsx
  client/src/components/course-view/UploadDialog.tsx
  client/src/components/course-view/UploadDialogConfirm.tsx
  client/src/components/course-view/UploadDialogUpload.tsx
  client/src/context/GradesTableProvider.tsx
  client/src/tests/mock-data/mockCourseParts.ts
  client/src/utils/table.ts
  common/types/coursePart.ts
  server/docs/coursePart.yaml
  server/src/controllers/coursePart.ts
  server/src/controllers/utils/coursePart.ts
  server/src/database/migrations/00020-add-max-grade.ts
  server/src/database/models/attainmentGrade.ts
  server/src/database/models/coursePart.ts
  server/test/controllers/coursePart.test.ts
  server/test/util/createData.ts
Labels: enhancement, frontend, backend

#799 Fix xmldom warning
  .eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/components/StudentsView.tsx
  client/src/components/course-results-view/CourseResultsTable.tsx
  common/package-lock.json
  common/package.json
  common/util/calculateGraph.ts
  e2e-tests/package-lock.json
  e2e-tests/package.json
  package-lock.json
  server/package-lock.json
  server/package.json
  server/src/controllers/utils/saml.ts
Labels: security

#797 A+ max grades
  client/src/components/course-view/CreateAplusCourseParts.tsx
  client/src/components/course-view/NewAplusCoursePartsDialog.tsx
  client/src/components/course-view/SelectAplusGradeSource.tsx
  client/src/components/course-view/SelectAplusGradeSources.tsx
  client/src/utils/utils.ts
  common/types/aplus.ts
  server/docs/aplus.yaml
  server/src/controllers/aplus.ts
  server/src/types/aplus.ts
  server/test/controllers/aplus.test.ts
Labels: frontend, backend, integration

#802 Fix production keys
  .gitignore
  client/Dockerfile.prod
  client/src/components/CourseView.tsx
  client/src/components/Header.tsx
  client/src/components/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course-results-view/PredictedGradeCell.tsx
  client/src/components/course-view/AddAplusGradeSourceDialog.tsx
  client/src/components/course-view/NewAplusCoursePartsDialog.tsx
  client/src/components/course-view/UploadDialog.tsx
  client/src/components/shared/PrettyChip.tsx
  docker-compose-from-images-dev.yaml
  docker-compose-from-images.yaml
  e2e-tests/playwright.config.ts
  reverse-proxy.conf
  reverse-proxy/Dockerfile
  server/dockerfiles/Dockerfile
  server/dockerfiles/Dockerfile.prod
  server/dockerfiles/Dockerfile.prod.run
  server/dockerfiles/Dockerfile.prod.run.dev
  server/src/middleware/errorHandler.ts
Labels: backend, security
