Repository aalto-grades/aalto-grades, pull requests merged in 2024-08, with the labels that each got.

#812 Improve mfa
  client/public/locales/en/translation.json
  client/public/locales/fi/translation.json
  client/public/locales/sv/translation.json
  client/src/App.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/OtpAuthDialog.tsx
  client/src/components/auth/ResetPasswordDialog.tsx
  client/src/components/auth/UserButton.tsx
  client/src/components/front-page/CreateCourseDialog.tsx
  client/src/hooks/api/auth.ts
  client/src/tests/Login.test.tsx
  common/types/auth.ts
  e2e-tests/tests/login.ts
  server/docs/auth.yaml
  server/src/configs/environment.ts
  server/src/controllers/auth.ts
  server/src/controllers/utils/auth.ts
  server/src/database/migrations/00022-add-mfa-confirmed.ts
  server/src/database/models/user.ts
  server/src/routes/auth.ts
  server/src/types/auth.ts
  server/test/controllers/auth.test.ts
  server/test/util/createData.ts
  server/test/util/getCookies.ts
Labels: enhancement, frontend, backend

#821 Fix e2e tests
  client/src/components/Header.tsx
  client/src/components/graph/Graph.tsx
  e2e-tests/tests/admin.spec.ts
  e2e-tests/tests/assistant.spec.ts
  e2e-tests/tests/teacher.spec.ts
Labels: bug, tests

#824 Fix useeffects
  client/src/components/ManageStudentsView.tsx
  client/src/components/course/CoursePartsView.tsx
  client/src/components/course/EditCourseView.tsx
  client/src/components/course/ModelsView.tsx
  client/src/components/course/course-parts-view/NewAplusCoursePartsDialog.tsx
  client/src/components/course/course-parts-view/SelectAplusCourse.tsx
  client/src/components/course/course-parts-view/SelectAplusGradeSources.tsx
  client/src/components/course/course-results-view/CourseResultsTableToolbar.tsx
  client/src/components/course/course-results-view/UserGraphDialog.tsx
  client/src/components/course/course-results-view/upload/AplusImportDialog.tsx
  client/src/components/course/course-results-view/upload/UploadDialog.tsx
  client/src/components/course/course-results-view/upload/UploadDialogUpload.tsx
  client/src/components/course/models-view/RenameGradingModelDialog.tsx
  client/src/components/shared/graph/CoursePartValuesDialog.tsx
  client/src/components/shared/graph/Graph.tsx
  client/src/components/shared/graph/SelectCoursePartsDialog.tsx
  client/src/components/shared/graph/graphUtil.ts
  client/src/components/shared/graph/nodes/AdditionNode.tsx
  client/src/components/shared/graph/nodes/AverageNode.tsx
  client/src/components/shared/graph/nodes/BaseNode.tsx
  client/src/components/shared/graph/nodes/CoursePartNode.tsx
  client/src/components/shared/graph/nodes/MaxNode.tsx
  client/src/components/shared/graph/nodes/MinPointsNode.tsx
  client/src/components/shared/graph/nodes/RequireNode.tsx
  client/src/components/shared/graph/nodes/RoundNode.tsx
  client/src/components/shared/graph/nodes/StepperNode.tsx
  client/src/components/shared/graph/nodes/SubstituteNode.tsx
  client/src/context/GraphProvider.tsx
Labels: frontend

#825 Utils translation keys
  client/public/locales/en/translation.json
  client/public/locales/fi/translation.json
  client/public/locales/sv/translation.json
  client/src/components/course/EditCourseView.tsx
  client/src/components/course/course-results-view/SisuDownloadDialog.tsx
  client/src/components/course/course-results-view/table/FinalGradeCell.tsx
  client/src/components/course/course-results-view/table/PredictedGradeCell.tsx
  client/src/components/front-page/CreateCourseDialog.tsx
  client/src/context/GradesTableProvider.tsx
  client/src/types/index.ts
  client/src/utils/table.ts
  client/src/utils/textFormat.ts
  client/src/utils/utils.ts
Labels: frontend

#845 Note about MFA in dev
  README.md
Labels: documentation

#847 Small fixes
  .eslintrc.json
  client/src/components/front-page/users/AddUserDialog.tsx
  client/src/components/login/ExternalAuth.tsx
  server/mock-data/users.sql
  server/src/middleware/requestLogger.ts
Labels: bug

#851 Don't log plaintext passwords
  server/src/middleware/requestLogger.ts
Labels: backend, security

#849 Course task bulk editing endpoint
  client/public/locales/en/translation.json
  client/public/locales/fi/translation.json
  client/public/locales/sv/translation.json
  client/src/components/course/CoursePartsView.tsx
  client/src/components/course/course-parts-view/NewAplusCourseTasksDialog.tsx
  client/src/hooks/api/courseTask.ts
  client/src/hooks/useApi.ts
  common/types/courseTask.ts
  common/types/general.ts
  common/types/graph.ts
  server/docs/courseTask.yaml
  server/src/controllers/courseTask.ts
  server/src/controllers/utils/courseTask.ts
  server/src/routes/courseTask.ts
  server/test/controllers/coursePart.test.ts
  server/test/controllers/courseTask.test.ts
  server/test/util/createData.ts
Labels: bug, frontend, backend

#853 Empty course redirection
  client/public/locales/en/translation.json
  client/public/locales/fi/translation.json
  client/public/locales/sv/translation.json
  client/src/App.tsx
  client/src/components/course/CoursePartsView.tsx
  client/src/components/course/CourseRedirect.tsx
  client/src/components/front-page/CourseTable.tsx
Labels: frontend, design

#854 Validate A+ API return values
  server/docs/logging.md
  server/src/controllers/aplus.ts
  server/src/controllers/utils/aplus.ts
  server/src/types/aplus.ts
Labels: backend, integration
